#!/usr/bin/env bash
# fw-handoff.sh — FW v2 · universal HANDOFF. IDENTICAL file in every project folder.
# ══════════════════════════════════════════════════════════════════════════════════
#   bash fw-handoff.sh "<one line>" [--note "<longer details>"] [--no-gate]
#
# v2 KEY CHANGE vs the old four scripts: the script WRITES THE RECORD ITSELF —
# NOW.md gets the entry prepended (newest-on-TOP, one convention everywhere) and
# SESSION-LOG.md gets an append. An unrecorded handoff is now impossible by
# construction (ps policed hand-edits and hard-failed; nd/cc only warned; all three
# could still end a session unsaved). Rich detail goes in --note, or hand-edit
# NOW.md first — this script never deletes what's there.
# Then, mechanically: INDEX.md regen (pure bash — no node dependency) → gate run +
# CACHED for fw-boot (.fw/gate-last) → CLAUDE.md snapshot sync (next chat auto-loads
# truth) → safe commit (stale-FUSE-lock-proof, verifies the commit LANDED) →
# ⚠ UNPUSHED alarm (the "6 commits sitting local" bug) → LEARNINGS nudge →
# honest elapsed clock → ONE final GREEN/RED line.
# Philosophy unified: ALWAYS SAVE, warn loudly, exit nonzero on any red.
set -u
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
. "$DIR/agent-ops-lib.sh"
[ -f "$DIR/.fw-config" ] && . "$DIR/.fw-config"
PROJECT="${FW_PROJECT:-$(basename "$DIR")}"

LINE="${1:-}"
if [ -z "$LINE" ] || [ "${LINE#--}" != "$LINE" ]; then
  echo 'usage: bash fw-handoff.sh "<one line: where we are · last: X · next: Y>" [--note "<details>"] [--no-gate]'
  exit 1
fi
shift || true
NOTE=""; NOGATE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --note) NOTE="${2:-}"; shift 2 ;;
    --no-gate) NOGATE=1; shift ;;
    *) shift ;;
  esac
done
TS="$(date '+%Y-%m-%d %H:%M')"
NOWFILE="${FW_NOW:-NOW.md}"
[ "$NOWFILE" = "STATE.md" ] && NOWFILE="NOW.md"   # never write a machine-swept STATE.md
RED=0

echo "── FW HANDOFF · $PROJECT · $TS ──"

# 1) WRITE THE RECORD (newest on top; keeps an existing '# ' header line on top)
ENTRY="$TS · $LINE"
[ -n "$NOTE" ] && ENTRY="$ENTRY
$NOTE"
STYLE="${FW_NOW_STYLE:-top}"   # bottom = append (repos whose NOW.md is an append-bottom log; keeps their own readers correct)
if [ "$STYLE" = "bottom" ] && [ -f "$NOWFILE" ]; then
  printf '\n%s\n' "$ENTRY" >> "$NOWFILE"
  echo "  ✓ $NOWFILE — entry appended ($TS · bottom-newest convention preserved)"
elif [ -f "$NOWFILE" ] && head -1 "$NOWFILE" | grep -q '^# '; then
  HDR="$(head -1 "$NOWFILE")"; BODY="$(tail -n +2 "$NOWFILE")"
  printf '%s\n\n%s\n%s\n' "$HDR" "$ENTRY" "$BODY" > "$NOWFILE"
  echo "  ✓ $NOWFILE — entry written on top ($TS)"
elif [ -f "$NOWFILE" ]; then
  BODY="$(cat "$NOWFILE")"
  printf '%s\n\n%s\n' "$ENTRY" "$BODY" > "$NOWFILE"
  echo "  ✓ $NOWFILE — entry written on top ($TS)"
else
  printf '# NOW — ground truth · newest entry on TOP · written by fw-handoff\n\n%s\n' "$ENTRY" > "$NOWFILE"
  echo "  ✓ $NOWFILE — created with first entry ($TS)"
fi
touch SESSION-LOG.md
printf -- '- %s — %s\n' "$TS" "$LINE" >> SESSION-LOG.md
echo "  ✓ SESSION-LOG.md appended"

# 2) INDEX.md — regenerate (grep the index, never re-read the tree). Repos with a
#    richer generator plug it in via FW_INDEX_CMD; everyone else gets the generic one.
if [ -n "${FW_INDEX_CMD:-}" ]; then
  if bash -c "$FW_INDEX_CMD" >/dev/null 2>&1; then echo "  ✓ INDEX via: $FW_INDEX_CMD"
  else echo "  ⚠ custom INDEX cmd failed ($FW_INDEX_CMD) — non-fatal"; fi
else
{
  echo "# INDEX — auto-generated by fw-handoff $TS. GREP ME instead of re-reading files."
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then git ls-files; else
    find . -type f 2>/dev/null | sed 's|^\./||'
  fi | grep -E '\.(sh|mjs|js|ts|tsx|py|sql|md|json)$' \
     | grep -vE '^(node_modules|\.next|\.git|out|dist|coverage|memory-archive|brain-vault)/' \
     | grep -vE '(^|/)(package-lock\.json|INDEX\.md)' \
     | head -"${FW_INDEX_MAX:-250}" | while IFS= read -r f; do
        [ -f "$f" ] || continue
        sz="$(wc -l < "$f" 2>/dev/null | tr -d ' ')"
        desc="$(head -5 "$f" 2>/dev/null | grep -m1 -E '^(#|//|/\*|\*|--)' | sed 's|^[#/* -]*||' | cut -c1-100 || true)"
        printf -- '- %s (%s) — %s\n' "$f" "${sz:-?}" "${desc:-·}"
     done
} > INDEX.md
NIDX="$(grep -c '^- ' INDEX.md 2>/dev/null)"
echo "  ✓ INDEX.md regenerated (${NIDX:-?} files indexed)"
fi

# 3) clear ALL genuinely-stale .git locks BEFORE the gate — HEAD.lock / maintenance.lock
#    block commits too; aol_safe_commit only handles index.lock (found live in
#    and the gate's lock check rightly flags them — so clear first, then gate).
#    Threshold is 5s, not 60: post-commit background maintenance leaves FRESH locks
#    (HEAD.lock/index.lock) that the mount refuses to unlink — and during fw-handoff no
#    other git process can legitimately be running in this folder.
fw_clear_locks() {
  [ -d .git ] || return 0
  # maxdepth 4, not 2: .git/refs/remotes/<remote>/<branch>.lock pinned CRM's tracking
  # ref on 2026-07-10 and a depth-2 sweep could never see it.
  find .git -maxdepth 4 -name '*.lock' 2>/dev/null | while IFS= read -r l; do
    age=$(( $(date +%s) - $(stat -c %Y "$l" 2>/dev/null || stat -f %m "$l" 2>/dev/null || echo 0) ))
    if [ "$age" -ge 5 ]; then
      # 2026-07-18 FREEZE: the old fallback renamed the lock IN PLACE — inside .git/refs
      # that artifact reads as a CORRUPT REF ("fatal: bad object ...lock.stale-N", found
      # 2026-07-20 CORRECTION: /tmp is a DIFFERENT filesystem than this FUSE mount, and a
      # cross-filesystem `mv` copies then deletes the source — that delete is exactly the
      # unlink() this mount denies, so the /tmp fallback silently left the ORIGINAL lock
      # still sitting there (confirmed live: source survived, blocking every commit after
      # it). Same-mount renames DO work here (also confirmed live) — just keep the
      # destination out of .git/refs so the original corrupt-ref bug can't recur.
      mkdir -p .fw-stale-locks
      { rm -f "$l" 2>/dev/null && [ ! -e "$l" ]; } || mv -f "$l" ".fw-stale-locks/$(basename "$l").stale-$(date +%s)" 2>/dev/null
      [ ! -e "$l" ] && echo "  · cleared stale git lock: $l (${age}s old)"
    fi
  done
}
fw_clear_locks

# 4) GATE — run + cache for fw-boot (boot never re-runs the suite)
mkdir -p .fw
GATECMD="${FW_GATE:-}"
[ -z "$GATECMD" ] && [ -f fw-verify.sh ] && GATECMD="bash fw-verify.sh"
GATE_TXT="none"
if [ "$NOGATE" = 1 ]; then
  GATE_TXT="skipped"
  echo "  · gate skipped (--no-gate)"
elif [ -n "$GATECMD" ]; then
  if OUT="$($GATECMD 2>&1)"; then
    GATE_TXT="GREEN"; echo "  ✓ gate GREEN ($GATECMD)"
  else
    GATE_TXT="RED"; RED=1
    printf '%s\n' "$OUT" | tail -6 | sed 's/^/    /'
    echo "  ✗ gate RED — state IS saved; fix before you ship."
  fi
  printf '%s @ %s' "$GATE_TXT" "$TS" > .fw/gate-last
else
  echo "  · no gate found (add fw-verify.sh or set FW_GATE in .fw-config)"
fi

# 5) CLAUDE.md auto-synced snapshot — the next chat loads truth with zero reads
#    (FW_CLAUDE_SYNC=0 for repos whose own brain owns the snapshot, e.g. cc-brain.js)
if [ "${FW_CLAUDE_SYNC:-1}" = "1" ]; then
  aol_sync_claude_snapshot CLAUDE.md NOW "**NOW (auto-synced by fw-handoff — do not edit by hand):** $TS · $LINE" || true
else
  echo "  · CLAUDE.md snapshot owned by this repo's own brain (FW_CLAUDE_SYNC=0)"
fi

# 5b) repo-specific handoff extras (brain rebuilds, snapshots, etc.)
if [ -n "${FW_HANDOFF_EXTRA:-}" ]; then
  echo "  · repo extras:"; bash -c "$FW_HANDOFF_EXTRA" 2>&1 | tail -4 | sed 's/^/    /'
fi

# 5) LEARNINGS nudge (warn-only — not every session earns a lesson)
if [ -f LEARNINGS.md ] && ! grep -q "$(date +%Y-%m-%d)" LEARNINGS.md 2>/dev/null; then
  echo "  ⚠ LEARNINGS.md has no entry dated today — if this session taught something, freeze it."
fi

# 6) COMMIT (stale-lock-proof — locks pre-cleared at step 3; verifies the commit landed;
#    cleanly no-ops when not a git repo)
aol_safe_commit "handoff: $LINE" . ; rc=$?
if [ "$rc" -eq 1 ] && [ -d .git ]; then
  echo "  ⟳ handoff-level retry: clearing lingering locks + re-committing…"
  sleep 5; fw_clear_locks
  aol_safe_commit "handoff: $LINE" . ; rc=$?
fi
[ "$rc" -eq 1 ] && RED=1
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  AHEAD="$(git rev-list --count @{u}..HEAD 2>/dev/null || echo '')"
  # L47 (2026-08-15): PUSH IS OPT-IN. This block auto-pushed unconditionally and fired
  # during an explicit no-push session. main = LIVE, so the deploy convenience stays one
  # flag away — FW_AUTO_PUSH=1 (env or .fw-config) restores the exact three-fallback
  # behavior below, unchanged. Default (unset/0) = commit-only + loud warning, like CRM.
  if [ -n "$AHEAD" ] && [ "$AHEAD" -gt 0 ] && [ "${FW_AUTO_PUSH:-0}" = "1" ]; then
    # 6b) AUTO-PUSH — three fallbacks, cheapest/fastest first.
    # network/proxy setup evolved — confirmed live 2026-07-20 that this repo's
    # device-bridge session has NO network access at all (by design), and a plain
    # usable credential for a personal repo either way. Kept both old attempts as
    # free first tries in case this script ever runs somewhere they'd work again —
    # but added a THIRD fallback that's actually proven reliable right now: the
    # no proxy, nothing that can drift out from under it the way the others did.
    # 2026-07-20. Full story: LEARNINGS.md 2026-07-20.
    PUSH_ERR="$(mktemp 2>/dev/null || echo /tmp/.fw-push-err.$$)"
    PUSH_OK=0; PUSH_HOW=""
    if git push origin HEAD >"$PUSH_ERR" 2>&1; then
      PUSH_OK=1; PUSH_HOW="direct"
    fi
    if [ "$PUSH_OK" -eq 1 ]; then
      echo "  ✓ pushed $AHEAD commit(s) to origin (auto-push: $PUSH_HOW)"
    else
      echo "  ⚠ $AHEAD commit(s) NOT PUSHED — auto-push tried (direct), all failed:"
      tail -6 "$PUSH_ERR" 2>/dev/null | sed 's/^/    /'
      echo "    Run 'git push' by hand."
    fi
    rm -f "$PUSH_ERR" 2>/dev/null
  elif [ -n "$AHEAD" ] && [ "$AHEAD" -gt 0 ]; then
    echo "  ⚠ $AHEAD commit(s) NOT PUSHED — FW_AUTO_PUSH=0 (default). Deploy deliberately: FW_AUTO_PUSH=1 bash fw-handoff.sh \"…\" — or 'git push' by hand."
  fi
fi

# 7) HONEST CLOCK — elapsed since fw-boot stamped the session start
CK="$(printf '%s' "$DIR" | cksum | cut -d' ' -f1)"; STAMP="/tmp/.fw-clock-$CK"
if [ -f "$STAMP" ]; then
  EL=$(( $(date +%s) - $(cat "$STAMP") ))
  printf '  ⏱  session elapsed: %dm %ds (boot → handoff)\n' $((EL/60)) $((EL%60))
  rm -f "$STAMP"
fi

# 8) ONE final line
if [ "$RED" -eq 0 ]; then
  echo "🟢 HANDOFF SAVED · $PROJECT · gate: $GATE_TXT · next chat: bash fw-boot.sh"
else
  echo "🔴 HANDOFF SAVED WITH ISSUES · $PROJECT · gate: $GATE_TXT — fix the ✗ lines above."
  exit 1
fi
